import type { CSSProperties } from 'react';

const footerStyle: CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'space-between',
  gap: 8,
  fontSize: 11,
  color: 'var(--color-ink-3)',
  paddingTop: 16,
  marginTop: 16,
  borderTop: '1px solid var(--color-hair)',
};
const btnStyle: CSSProperties = {
  background: 'rgba(255,255,255,0.05)',
  border: '1px solid rgba(255,255,255,0.08)',
  color: 'var(--color-ink-2)',
  borderRadius: 6,
  padding: '4px 8px',
  fontSize: 11,
  cursor: 'pointer',
};

export function BriefFooter({
  provider,
  cost,
  rating,
  onRate,
  onRegenerate,
}: {
  provider: string;
  cost: number;
  rating: -1 | 1 | null;
  onRate: (r: -1 | 1) => void;
  onRegenerate: () => void;
}) {
  const costStr = cost.toFixed(4);
  return (
    <div style={footerStyle}>
      <span>
        Generated by {provider} · ${costStr}
      </span>
      <div style={{ display: 'flex', gap: 6 }}>
        <button
          type="button"
          style={btnStyle}
          aria-label="Thumbs up"
          aria-pressed={rating === 1}
          onClick={() => onRate(1)}
        >
          👍
        </button>
        <button
          type="button"
          style={btnStyle}
          aria-label="Thumbs down"
          aria-pressed={rating === -1}
          onClick={() => onRate(-1)}
        >
          👎
        </button>
        <button type="button" style={btnStyle} onClick={onRegenerate}>
          Regenerate
        </button>
      </div>
    </div>
  );
}
