export { Icon, type IconProps } from './Icon.js';
export {
  IconCompass,
  IconHome,
  IconNote,
  IconFocus,
  IconGoal,
  IconInbox,
  IconBlock,
  IconGear,
  IconSearch,
  IconPlus,
  IconChevron,
  IconUp,
  IconDown,
  IconCheck,
  IconClose,
  IconPlay,
  IconPause,
  IconSun,
  IconMoon,
  IconSpark,
  IconMic,
  IconLink,
  IconStar,
  IconDrop,
  IconSleep,
  IconHeart,
  IconCloud,
  IconCalendar,
  IconClock,
  IconPeople,
  IconKey,
  IconThumbUp,
  IconThumbDown,
  IconSend,
  IconWand,
  IconSound,
  IconEye,
  IconEyeOff,
  IconSliders,
  IconMore,
  IconArrow,
} from './icons.js';

import {
  IconCompass,
  IconHome,
  IconNote,
  IconFocus,
  IconGoal,
  IconInbox,
  IconBlock,
  IconGear,
  IconSearch,
  IconPlus,
  IconChevron,
  IconUp,
  IconDown,
  IconCheck,
  IconClose,
  IconPlay,
  IconPause,
  IconSun,
  IconMoon,
  IconSpark,
  IconMic,
  IconLink,
  IconStar,
  IconDrop,
  IconSleep,
  IconHeart,
  IconCloud,
  IconCalendar,
  IconClock,
  IconPeople,
  IconKey,
  IconThumbUp,
  IconThumbDown,
  IconSend,
  IconWand,
  IconSound,
  IconEye,
  IconEyeOff,
  IconSliders,
  IconMore,
  IconArrow,
} from './icons.js';

/**
 * Dynamic-lookup map keyed by prototype name. Used by the sidebar, where an
 * icon name arrives as a string from a nav-items config.
 */
export const ICONS = {
  compass: IconCompass,
  home: IconHome,
  note: IconNote,
  focus: IconFocus,
  goal: IconGoal,
  inbox: IconInbox,
  block: IconBlock,
  gear: IconGear,
  search: IconSearch,
  plus: IconPlus,
  chevron: IconChevron,
  up: IconUp,
  down: IconDown,
  check: IconCheck,
  close: IconClose,
  play: IconPlay,
  pause: IconPause,
  sun: IconSun,
  moon: IconMoon,
  spark: IconSpark,
  mic: IconMic,
  link: IconLink,
  star: IconStar,
  drop: IconDrop,
  sleep: IconSleep,
  heart: IconHeart,
  cloud: IconCloud,
  calendar: IconCalendar,
  clock: IconClock,
  people: IconPeople,
  key: IconKey,
  thumbUp: IconThumbUp,
  thumbDown: IconThumbDown,
  send: IconSend,
  wand: IconWand,
  sound: IconSound,
  eye: IconEye,
  eyeOff: IconEyeOff,
  sliders: IconSliders,
  more: IconMore,
  arrow: IconArrow,
} as const;

export type IconName = keyof typeof ICONS;
